### ISSUE TITLE
How to use this code to gain POS tag vectors and CCG supertag vectors of a specified data？

### ISSUE THREAD

**Issue by yuquanle** [wangshaonan/Learning-sentence-representation-with-guidance-of-human-attention#1]
Dear wangshaonan:
      Hello, I am very interested in your paper, can you write a simple demo to generate a specified data's POS tag vectors and CCG supertag vectors?.
                                                                                                                                                       best wish！

**Comment by wangshaonan** [comment]
I add some example training data and word embedding data. Now you can just run run.sh. Then you will get word-pos-model.pkl, which contain all network parameters, including pos tag vectors. You need to use full training and word embedding data to get a better result. In the same way, you can get the CCG supertag vectors. Hope this will help.

**Comment by wangshaonan** [comment]
Hi,

I add some example training data and word embedding data. Now you can just run run.sh. Then you will get word-pos-model.pkl, which contain all network parameters, including pos tag vectors. You need to use full training and word embedding data to get a better result. In the same way, you can get the CCG supertag vectors. Hope this will help.




wangshaonan2013@ia.ac.cn
 
发件人： yuquanle
发送时间： 2017-07-30 09:34
收件人： wangshaonan/Learning-sentence-representation-with-guidance-of-human-attention
抄送： Subscribed
主题： [wangshaonan/Learning-sentence-representation-with-guidance-of-human-attention] How to use this code to gain POS tag vectors and CCG supertag vectors of a specified data？ (#1)
Dear wangshaonan:
Hello, I am very interested in your paper, can you write a simple demo to generate a specified data's POS tag vectors and CCG supertag vectors?.
best wish！

**Comment by yuquanle** [comment]
Dear wangshaonan:
I am very honored to get your reply. These days I ran you to provide the source. Due to I am not familiar with theano, I encountered a problem::

![1](https://user-images.githubusercontent.com/20789703/29245362-91e7fedc-800a-11e7-81b6-baf1dc117a66.png)


PS：
My linux system environment is：
Ubuntu 14.04
python 2.7
theano 0.9.0

best wish！

**Comment by yuquanle** [comment]
Dear wangshaonan:
I am very honored to get your reply. These days I have built the theano environment and ran your provided code and got word-pos-model.pkl. As is shown in Fig:
![1](https://user-images.githubusercontent.com/20789703/29245620-7782e8ec-8012-11e7-8862-2b82fa36ad35.png)


In your paper the use of word's POS tag vectors (or CCG supertag vectors) and word embedding vector to calculate the weight of the word (attention mechanism weight). Finally, the sentence vector is calculated by :

![2](https://user-images.githubusercontent.com/20789703/29245682-c8fe0d30-8014-11e7-928d-69384805836a.png)

Because of my current research needs, I want to get the  attention mechanism weight of every word in a sentence's (word's POS tag vectors or CCG supertag vectors) , but by looking at word-pos-model.pkl, I do not know what to do next. Can you give some guidance?

**Comment by wangshaonan** [comment]
you need to read in .pkl to see the result. you need to import pickle in python and use pickle.load(open(filename)), then print the result or write it into txt.

maybe the following code will help.

import cPickle as pickle
pp = pickle.load(open('word-pos-model.pkl'))
embedding = pp[0].get_value()
pos_embedding = pp[1].get_value()

then based on your data, you need to calculate the dot product of each word embedding and its pos embedding

**Comment by yuquanle** [comment]
Hi wangshaonan:

I've been reading your paper recently, and I think it makes sense for the three kinds of weight that you've introduced in the article(word'Surprisal,POS tags and CCG).


For a specific sentence, for example, "the activity of learning or being trained	the gradual process of acquiring knowledge." comes from STS 2014 task data.


How to get each word's attention weight(through CCG,POS and Surprisal methods).I would like to have a specific example to tell people how to operate.


(I have trained word embedding through Wikipedia.How should I apply it?)

I think the people behind will have the same questions.

                                                                                                                                       Best wishs！
